### ISSUE TITLE
License and webpage also scrolls if you add any additional content to the page. 

### ISSUE THREAD

**Issue by vm0303** [PiggyDiggy/2048#1]
Hello PiggyDiggy,

I was inspired in the way you did the 2048 game using Vue.js, and decided to mimic something similar. (More details on how I did my version is stated in my second question). However, I have two questions

1. What is the license for this? 
Just because I was inspired, I don't want you to feel like I just copied your code and claimed that I did the work. (In my footer, I did give credit to you and a YouTube tutorial that I saw.)

![image](https://user-images.githubusercontent.com/57302592/219198449-bc6619b3-8c83-46fa-af98-090308164e7b.png)

I want to make sure that I can give credit where credit is due. 

2. In my version, I have additional information like the objective of the game and how to play in text instead of just the board itself. I also have a leaderboard integrated with Google Firestore where once a user is done with the game, they can either restart the game or report their score in that score form. My question to you is when a user swipes the board up or down on a mobile device with any additional things added to the webpage, the whole page scrolls up or down as shown in the gif below. 

![Issue](https://user-images.githubusercontent.com/57302592/219474473-a02cfdbc-392c-4671-a7d2-f3ea7f030e72.gif)

I have tried various methods using document.addEventListner to just listen to the game container events rather than the body of the page so that I don't have that issue, but it doesn't seem to work. Then I tried to import VueTouch, but that also failed as well.
So I was wondering if you have any tips on how I can not make the whole page scrolls up or down when a user is swiping the board.

**Comment by PiggyDiggy** [comment]
https://github.com/vm0303/2048-Using-Vue-And-Firestore/blob/6425a3b527b3e187ba29b380ae99fd0182772ca2/2048-game/src/App.vue#L16
```js
document.addEventListener('touchmove', function (e) {
  e.preventDefault();
}, {passive: false});
```

**Comment by PiggyDiggy** [comment]
1. Everything is good, keep it like that
2. Follow these steps:
- [Delete this listener](https://github.com/vm0303/2048-Using-Vue-And-Firestore/blob/6425a3b527b3e187ba29b380ae99fd0182772ca2/2048-game/src/App.vue#L16)
```js
document.addEventListener('touchmove', function (e) {
  e.preventDefault();
}, {passive: false});
```
- [Prevent default behavior here](https://github.com/vm0303/2048-Using-Vue-And-Firestore/blob/6425a3b527b3e187ba29b380ae99fd0182772ca2/2048-game/src/utils/TouchEvents/TouchMobileEvents.js#L28)
```js
handleMove(e) {
    e.preventDefault(); // <-- here
    if (this.dispatched) return;
    const {clientX: x, clientY: y} = e.touches[0];
    // ...
}
```
- [Add ref to grid element](https://github.com/vm0303/2048-Using-Vue-And-Firestore/blob/6425a3b527b3e187ba29b380ae99fd0182772ca2/2048-game/src/components/TheGridAndScore.vue#L35)
```js
<div :class="{ restarting }" class="grid" ref="grid">
  <TheTile v-for="tile in tiles" :key="tile.id" :tile="tile"/>
</div>
```
- [Move this object initialization to mounted hook](https://github.com/vm0303/2048-Using-Vue-And-Firestore/blob/6425a3b527b3e187ba29b380ae99fd0182772ca2/2048-game/src/components/TheGridAndScore.vue#L141)
```js
mounted() {
    const gridRef = this.$refs.grid;
    new TouchMobileEvents(gridRef);
    gridRef.addEventListener("custom:swipe", ({ detail }) => this.swipe(detail));
}
```

**Comment by vm0303** [comment]
Hey PiggyDiggy,

Thank so much for the reply and help! After leaving the footer as it is and making the changes you suggested, it works flawlessly! I have almost given up by removing this Swipe.js file and importing various Vue Touch libraries because I was getting a little frustrated. 

Have a wonderful day!
